#!/usr/bin/env python3
"""
Structural validation for the n8n workflow JSON files under
n8n/workflows/ (Phase 5/6 -- external scheduler/automation clock).

Does NOT require a running n8n instance (none was available in this
environment -- see the completion report for what that would add).
Validates what CAN be verified statically: the JSON parses, every
workflow has the expected node/connection shape for n8n's import
format, no node references a name that doesn't exist, no secret-shaped
string is committed, no candidate_id is hardcoded to a real value, no
SQLite path is referenced anywhere, and the search-runner workflow only
ever calls the existing /api/scheduler/run-due endpoint (never a second
scheduling or search-execution implementation).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = ROOT / "n8n" / "workflows"

passed = 0
failed = 0


def check(cond, msg):
    global passed, failed
    if cond:
        passed += 1
        print(f"PASS: {msg}")
    else:
        failed += 1
        print(f"FAIL: {msg}")


workflow_files = sorted(WORKFLOWS_DIR.glob("*.json"))
check(len(workflow_files) >= 2, f"at least 2 workflow files exist under n8n/workflows/, got {[f.name for f in workflow_files]}")

SECRET_PATTERNS = [
    re.compile(r"sk-[a-zA-Z0-9]{10,}"),
    re.compile(r"(?i)authorization[\"']?\s*:\s*[\"']bearer"),
    re.compile(r"(?i)api[_-]?key[\"']?\s*:\s*[\"'][a-zA-Z0-9]{12,}"),
    re.compile(r"(?i)password[\"']?\s*:\s*[\"'][^\"']{3,}"),
]
KNOWN_CANDIDATE_ID_PATTERN = re.compile(r"cand_[0-9a-f]{8,}")

for wf_path in workflow_files:
    raw_text = wf_path.read_text()
    label = wf_path.name

    try:
        wf = json.loads(raw_text)
    except json.JSONDecodeError as error:
        check(False, f"{label}: parses as valid JSON (error: {error})")
        continue
    check(True, f"{label}: parses as valid JSON")

    # Real defect found via live n8n CLI import (n8n 2.39.8): without a
    # top-level workflow "id", `n8n import:workflow` fails with
    # "SQLITE_CONSTRAINT: NOT NULL constraint failed: workflow_entity.id"
    # -- confirmed live against a real n8n container, not just a JSON
    # schema assumption. A non-empty string id is required for a real
    # import to succeed, not just for the file to parse as JSON.
    check(isinstance(wf.get("id"), str) and len(wf["id"]) > 0, f"{label}: has a non-empty top-level 'id' (required for a real n8n import to succeed, not just JSON parsing)")

    check("nodes" in wf and isinstance(wf["nodes"], list) and len(wf["nodes"]) > 0, f"{label}: has a non-empty 'nodes' array")
    check("connections" in wf and isinstance(wf["connections"], dict), f"{label}: has a 'connections' object")
    check(wf.get("active") is False, f"{label}: imports as inactive (never auto-activates without a human enabling it)")

    node_names = [n.get("name") for n in wf["nodes"]]
    check(len(node_names) == len(set(node_names)), f"{label}: no duplicate node names, got {node_names}")

    required_node_fields = {"id", "name", "type", "typeVersion", "position", "parameters"}
    missing_fields = [n.get("name") for n in wf["nodes"] if not required_node_fields.issubset(n.keys())]
    check(missing_fields == [], f"{label}: every node has id/name/type/typeVersion/position/parameters, missing on: {missing_fields}")

    # Every connection source and target must reference a real node name.
    node_name_set = set(node_names)
    bad_refs = []
    for source_name, outputs in wf["connections"].items():
        if source_name not in node_name_set:
            bad_refs.append(("source", source_name))
        for branch in outputs.get("main", []):
            for edge in branch:
                target = edge.get("node")
                if target not in node_name_set:
                    bad_refs.append(("target", target))
    check(bad_refs == [], f"{label}: every connection references a real node name, bad refs: {bad_refs}")

    # A trigger node exists (schedule trigger -- this is a scheduled
    # automation, not a manually-run-only workflow).
    trigger_types = [n["type"] for n in wf["nodes"] if "trigger" in n["type"].lower()]
    check(len(trigger_types) >= 1, f"{label}: has at least one trigger node, got {trigger_types}")

    # No secret-shaped literal string anywhere in the committed file.
    secret_hits = [p.pattern for p in SECRET_PATTERNS if p.search(raw_text)]
    check(secret_hits == [], f"{label}: no secret-shaped string committed, got pattern matches: {secret_hits}")

    # No real candidate_id value committed (a real one always looks
    # like cand_<hex>, generated by profile_store.create_candidate()).
    check(not KNOWN_CANDIDATE_ID_PATTERN.search(raw_text), f"{label}: no real-looking candidate_id value is hardcoded")

    # No actual SQLite file PATH referenced anywhere -- every read/
    # write goes through the JobOS HTTP API, never a direct DB file.
    # Checks for a real filesystem path shape (a "/" immediately
    # before the filename), not a bare filename mentioned in the
    # sticky-note prose explaining which port maps to which database
    # (e.g. "127.0.0.1:8421, jobos.db") -- that's human-readable
    # context, not a file-access mechanism this workflow could ever
    # execute (no node type here can open a local file at all).
    sqlite_path_pattern = re.compile(r"[/\\](jobos(_dev)?\.db|[\w.-]+\.sqlite)\b", re.IGNORECASE)
    check(
        not sqlite_path_pattern.search(raw_text),
        f"{label}: no actual SQLite file PATH referenced anywhere (bare filename mentions in prose are fine)",
    )

check(
    "/api/scheduler/run-due" in (WORKFLOWS_DIR / "jobos_scheduled_search_runner.json").read_text(),
    "jobos_scheduled_search_runner.json: calls the EXISTING /api/scheduler/run-due endpoint",
)
runner_text = (WORKFLOWS_DIR / "jobos_scheduled_search_runner.json").read_text()
check(
    "/api/searches" not in runner_text and "trigger_run" not in runner_text.lower().replace("_", ""),
    "jobos_scheduled_search_runner.json: never calls a per-search run endpoint directly or reimplements trigger_run itself -- delegates entirely to run-due",
)

check(
    "/api/candidates/" in (WORKFLOWS_DIR / "jobos_follow_up_reminder.json").read_text()
    and "/follow-ups" in (WORKFLOWS_DIR / "jobos_follow_up_reminder.json").read_text(),
    "jobos_follow_up_reminder.json: calls the candidate-scoped GET .../follow-ups endpoint",
)
follow_up_text = (WORKFLOWS_DIR / "jobos_follow_up_reminder.json").read_text()
check(
    '"method": "POST"' not in follow_up_text and '"method": "PATCH"' not in follow_up_text,
    "jobos_follow_up_reminder.json: is read-only (no POST/PATCH call anywhere) -- never writes back to JobOS",
)

print()
print(f"{passed} passed, {failed} failed")
if failed:
    sys.exit(1)
